apiVersion: v1
kind: Service
metadata:
  name: idea-backlog
  namespace: idea-backlog
  labels:
    app: idea-backlog
spec:
  selector:
    app: idea-backlog
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
